// File generated by Antigravity for Firebase initialization.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return android;
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7Lb24Fooo6kpR_FhK3B6nrlADqXmNm60',
    appId: '1:515120879902:android:a5a502821dd575eaacd10f',
    messagingSenderId: '515120879902',
    projectId: 'elaraby-workforce-222d2',
    storageBucket: 'elaraby-workforce-222d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Lb24Fooo6kpR_FhK3B6nrlADqXmNm60',
    appId: '1:515120879902:android:a5a502821dd575eaacd10f',
    messagingSenderId: '515120879902',
    projectId: 'elaraby-workforce-222d2',
    storageBucket: 'elaraby-workforce-222d2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Lb24Fooo6kpR_FhK3B6nrlADqXmNm60',
    appId: '1:515120879902:android:a5a502821dd575eaacd10f',
    messagingSenderId: '515120879902',
    projectId: 'elaraby-workforce-222d2',
    storageBucket: 'elaraby-workforce-222d2.firebasestorage.app',
  );
}
